exclude: ['bower_components', 'node_modules']
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
path: http://lukaszfiszer.github.io/drag-n-crop